### ISSUE TITLE
Question about training settings

### ISSUE THREAD

**Issue by shanice-l** [liuyuan-pal/Gen6D#1]
Hi, authors!

Thank you for your inspiring work! However, I have a question about the training settings. 

In the paper, you mentioned that you train the network on ShapeNet and Google Scanned Object,  but I'd like to know more details. For example, what's the way you generate training data, how many epochs do you train the network and how long does it take?

Looking forward to your reply!

**Comment by liuyuan-pal** [comment]
Hi, thanks for your interest.

The training set is generated separately for the detector, selector and refiner.

- For the detector, we randomly paste an object on an image from the COCO dataset as the query image. We use some other images from different viewpoints (FPS sampling on camera locations) of this object as reference images. Then, the detector is applied to find the object on the query image for training.
- For the selector, we randomly select an image of the object as a query image and use images of the object from other viewpoints as reference images. The selector is applied to select the viewpoint that is nearest to the query image for training.
- For the refiner, we randomly select an image as the query image and we add disturbance to its ground-truth pose as the input pose. Then, the refiner is applied to refine the input pose to the ground-truth pose for training.

We've trained them for about 300k steps on a single 1080ti GPU, which costs about 3 days for the detector, 3 days for the selector and 1 day for the refiner.

We'll release both codes and datasets once the paper is going to be published.

Thank you.

**Comment by shanice-l** [comment]
Thanks for your timely reply! 

Your paper is of high quality and definitely worth publishing at the top conference. Wish you good luck!
