### ISSUE TITLE
About selected objects from GSO dataset

### ISSUE THREAD

**Issue by shanice-l** [liuyuan-pal/Gen6D#10]
Hi, authors!

Thanks for your work. 
I've noticed that you chose some models from the GSO dataset for training. I'm wondering if you pick those models on purpose or randomly selected some? And the model names downloaded from [onedrive](https://connecthkuhk-my.sharepoint.com/personal/yuanly_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyuanly%5Fconnect%5Fhku%5Fhk%2FDocuments%2FGen6D&ga=1) are different from the [official link](https://app.ignitionrobotics.org/GoogleResearch/fuel/collections/Google%20Scanned%20Objects), could you please offer me a list with the selected raw model names?

RSVP.

**Comment by liuyuan-pal** [comment]
Hi, I manually rule out symmetric objects which may result in ambiguity in training. Symmetric object names are list in https://github.com/liuyuan-pal/Gen6D/blob/main/assets/gso_sym.txt

**Comment by shanice-l** [comment]
Thanks for your reply!

But the model names from https://github.com/liuyuan-pal/Gen6D/blob/main/assets/gso_sym.txt are still different from the [official link](https://app.ignitionrobotics.org/GoogleResearch/fuel/collections/Google%20Scanned%20Objects), so I don't know which models do they correspond with.

For example, the names from the GSO website are just like "YumYum_D3_Liquid"/"ZigKick_Hoops", but the names in your repo are in the format like "hN6VWtwq96u"/"Fb7Ffb1zM46".

**Comment by liuyuan-pal** [comment]
Hi, I directly use the renderings from IBRNet https://drive.google.com/drive/folders/1qfcPffMy8-rmZjbapLAtdrKwg3AV-NJe?usp=sharing
I'm sorry that I also don't know which model the renderings correspond to.
