### ISSUE TITLE
Error in training  "ValueError: 'a' and 'p' must have same size"

### ISSUE THREAD

**Issue by EvdoTheo** [liuyuan-pal/Gen6D#119]
Hello @liuyuan-pal , I'm encountering an error whenever I'm about to start training either of the selector, detector or refiner. I noticed that the problem comes from the parameter **use_database_sample_prob: true** in the config files, so when I change it to **false**, the error doesn't appear anymore. Could you please explain the purpose of this parameter and how it affects the training if I turn it to false? Thank you!

**Comment by liuyuan-pal** [comment]
Hi, I predefine several sample probabilities here
https://github.com/liuyuan-pal/Gen6D/blob/50aa71b2dbb3198772c025d54d0dd191a918982c/dataset/train_dataset.py#L196
It seems that I do not have access to the data here.
