### ISSUE TITLE
About meta_info

### ISSUE THREAD

**Issue by CharlesHuan** [liuyuan-pal/Gen6D#12]
Dear authors,

thanks for your great work!

I was trying to make my own custom object to track and was following your tutorial.，I have some questions :
my  custom meta_info.txt like this:
![meta](https://user-images.githubusercontent.com/47875698/183367536-ba520ced-6b33-4c23-9375-b5a7dad3898a.png)
It's based on
![meta_info](https://user-images.githubusercontent.com/47875698/183367060-52741fb6-f137-4cac-884f-7df7868fa3bd.png)
the visualizations I got weren't good enough,like this:

![0](https://user-images.githubusercontent.com/47875698/183367846-b7c617aa-5170-46bc-a1ab-563ccffbf1e9.jpg)

but directly download the reference images processed by you at [here](https://connecthkuhk-my.sharepoint.com/:f:/g/personal/yuanly_connect_hku_hk/EkWESLayIVdEov4YlVrRShQBkOVTJwgK0bjF7chFg2GrBg?e=Y8UpXu) (mouse_processed.tar.gz) ,could get a good visualizations ,like this:
![0](https://user-images.githubusercontent.com/47875698/183370115-27a706ab-69d2-45f0-93c8-7913042fe33d.jpg)

so I guess the problem maybe appear in my meta info.txt
I need some help T-T

**Comment by omarirfa** [comment]
Hi,

You may have already seen this issue but just wanted to ask if you also looked at this issue regarding metainfo? #7

**Comment by CharlesHuan** [comment]
yes，I look at this issue regarding metainfo and followed similar steps from there to create my metainfo file https://github.com/liuyuan-pal/Gen6D/issues/7,x+(the X+ direction for the object is(2.271052 0.032156 -0.296206)).like this
![X+](https://user-images.githubusercontent.com/47875698/183546108-d15a6438-64c8-430b-bffc-27f1111428e8.png)
and z-(visualize the normal and use the normal as the Z direction,The normal is shown in the left-bottom panel. Note that the normal is opposite to the Z+ direction (up), so the Z+ direction for the object is (-0.0992386 -0.573665 -0.813056)),like this
![Z-](https://user-images.githubusercontent.com/47875698/183546401-941d4757-c157-4d70-8305-93901bfa2175.png)
my meta_info like this(It's also shown in the description, but just to make sure I follow https://github.com/liuyuan-pal/Gen6D/issues/7):
![meta](https://user-images.githubusercontent.com/47875698/183547114-8bbd0408-bcb3-4e46-88a4-6a1c19401d0e.png)
I have the following files, which are generated by above steps.
![目录结构](https://user-images.githubusercontent.com/47875698/183549294-2fee9817-bc54-43bc-a96c-2a739eb085ce.png)

and I predict poses for the test video by these command:
python predict.py --cfg configs/gen6d_pretrain.yaml \
                  --database custom/mouse \
                  --video data/custom/video/mouse-test.mp4 \
                  --resolution 960 \
                  --transpose \
                  --output data/custom/mouse/test \
                  --ffmpeg ffmpeg 
I don't know exactly where it went wrong.T-T

**Comment by omarirfa** [comment]
Strange I also get different results but it is not similar at all to the original one for the mouse. Could you post your segmented mouse i.e. your object_point_cloud.ply? I think @liuyuan-pal can best comment on this since I have also encountered this similar issue while using the code. I am guessing its how the segmentation is being done based on this issue #7 but I am unsure.

Images_Inter:
![0](https://user-images.githubusercontent.com/61637151/183553846-2b25b6b0-1d9b-47a6-b6ea-941a24d6937a.jpg)

Object_point_cloud.ply:
![image](https://user-images.githubusercontent.com/61637151/183553999-0f006ce1-3642-404f-9bd8-b2899eb7974f.png)

**Comment by CharlesHuan** [comment]
Strange I think my object_point_cloud.ply is accurate，like this：
![ply](https://user-images.githubusercontent.com/47875698/183558874-d32e7d2f-4bef-4228-97fc-360db1b704c4.png)

**Comment by omarirfa** [comment]
Oh you didnt segment it again? this is the original file i believe

**Comment by CharlesHuan** [comment]
> Oh you didnt segment it by yourself? this is the original file i believe. Unsure tbh what the problem is then

This is actually my own segmented image T-T, because the segmentation is pretty accurate, except for Z + and X +, these is visually very similar.

**Comment by liuyuan-pal** [comment]
Hi, @CharlesHuan it seems that your `object_point_cloud.ply` has some problem so that the generated reference images are not centered on the object: (since we use the `object_point_cloud.ply` to specify the object (size and center) you want to track.)
![image](https://user-images.githubusercontent.com/23974453/183577051-a511a512-4cc0-4e0e-8b62-737c02dbdd48.png)
The reference images should look like:
![image](https://user-images.githubusercontent.com/23974453/183577525-20d1e365-7428-4ef1-8b3b-7bd9bb7d19b0.png)

**Comment by CharlesHuan** [comment]
> Hi, @CharlesHuan it seems that your `object_point_cloud.ply` has some problem so that the generated reference images are not centered on the object: (since we use the `object_point_cloud.ply` to specify the object (size and center) you want to track.) ![image](https://user-images.githubusercontent.com/23974453/183577051-a511a512-4cc0-4e0e-8b62-737c02dbdd48.png) The reference images should look like: ![image](https://user-images.githubusercontent.com/23974453/183577525-20d1e365-7428-4ef1-8b3b-7bd9bb7d19b0.png)
> 
> You may open both the `pointcloud.ply` and `object_point_cloud.ply` in the same CloudCompare windows to see if they are aligned or not.

Thanks for your reply！Through your prompts，I found problems in generating database：
It should be like this
![9719df974f0f1154f02b1e6d271c257](https://user-images.githubusercontent.com/47875698/183612625-8591832e-f2ba-4fd5-8d2c-7483d5d65ec3.jpg)
but dense clouds generated by the GUI I used,maybe cause the database to be misaligned with the generated cloud.
The problem has now been solved,thanks again！
