### ISSUE TITLE
Custom Object prediction - "Attempting to deserialize object on a CUDA device" exception

### ISSUE THREAD

**Issue by blo85** [liuyuan-pal/Gen6D#15]
Hello,

First of all thank you for the work provided here.
I have been following step by step the manual to add custom objects, and everything has been OK, but when launching the last prediciton command I am encountering this error:

![image](https://user-images.githubusercontent.com/722665/186215008-6b20d67e-1f0f-4235-bcb6-56f7db4c6332.png)

_raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU._

I have tried the device cpu option suggested, but it doesn't work either.

I would say that I have everything installed correctly, I have followed the main instructions and I have followed the requirements:
![image](https://user-images.githubusercontent.com/722665/186216849-b40c19d9-aabf-4aa2-a364-e705f8b55486.png)

Any idea what could be going on? thank you very much!

**Comment by liuyuan-pal** [comment]
Hi, it seems that you only install a cpu version of Pytorch.
![image](https://user-images.githubusercontent.com/23974453/186330578-788fc741-e62d-4500-ab52-c114894fb1b5.png)

**Comment by blo85** [comment]
Thank you for your response.

You are right, I hadn't noticed when creating the CONDA ENV. Sometimes by wanting to do things too fast..., you have the problem in front of you and you don't see it....

I mark this as solved, and continue with the rest of the steps.

BR
