### ISSUE TITLE
cameras.bin provided in mouse_processed.tar.gz contains nothing.

### ISSUE THREAD

**Issue by saprrow** [liuyuan-pal/Gen6D#18]
I tried to use mouse_processed.tar.gz to run pose estimation on custom objects, while I got this Error:
![Screenshot from 2022-09-20 10-43-43](https://user-images.githubusercontent.com/44662300/191156126-89739ebf-a5b2-4e1a-9b58-264395142125.png)
After reading it with python,  I found it contains nothing:
![Screenshot from 2022-09-20 10-46-51](https://user-images.githubusercontent.com/44662300/191156342-97c7041a-e78d-4928-b362-21abe8cc4b22.png)

Could you please provide the right cameras.bin in mouse_processed.tar.gz? Thanks!

**Comment by liuyuan-pal** [comment]
Hi, it seems the file works fine on my laptop.
![image](https://user-images.githubusercontent.com/23974453/191637633-727d3bef-28c2-474f-8618-64217a310862.png)

Maybe, you can re-download the file and read it again.

**Comment by saprrow** [comment]
I indeed redownloaded the file and read nothing from camera.bin. After receiving your reply, I 3rd redownloaded the file and found it works well magically 😂.  Thanks! Sorry for bothering.

**Comment by liuyuan-pal** [comment]
Maybe, it was caused by some mysterious errors in OneDrive 😂
