### ISSUE TITLE
why don't use cropped image when training selector?

### ISSUE THREAD

**Issue by dedoogong** [liuyuan-pal/Gen6D#20]
After reviewed your code, I found, it uses the whole original image when training selector.
is there a some reason? why it doesn't use object-centric cropped images?

Plus, my custom dataset is generated by a 3D modeling tool (so it's not real data). 
And the world environment of the object is keep changing(So, background image and light color/intensity change every frame by frame) while spinning the virtual camera. 
Does this kind of augmentation make a bad impact on training selector? I think your model already use COCO dataset to augment background when using custom training data. So isn't OK?

Thank you!

**Comment by liuyuan-pal** [comment]
It's fine to use the cropped images. The default training data mainly consist of synthetic data which is only 128x128, so I just read the whole image for convenience. The other real training data indeed requires cropping and resizing after reading. You can crop and resize them beforehand and read the processed images.
