### ISSUE TITLE
Pose output

### ISSUE THREAD

**Issue by omarirfa** [liuyuan-pal/Gen6D#3]
Hi, 

This is a very interesting paper and I was just trying out the code for custom objects. I was wondering if it outputs the 6d pose for the object that is being tracked in the video? For example the mouse video

**Comment by liuyuan-pal** [comment]
Hi, the output pose is saved in this directory, which is [R;t] of x_camera = R @ x_world + t.
https://github.com/liuyuan-pal/Gen6D/blob/ef133ae972e694a5bbb492f05f96ff1137e11e0c/predict.py#L60

**Comment by omarirfa** [comment]
Ah okay. I loaded in the .npy file and wanted to clarify how the poses are arranged. In the picture below, is the last column (-0.39157546,-1.5519593,4.633037) the pitch, roll, and yaw? If that is true are the first three columns the x,y,z coordinates?

.npy pose loaded in:
![image](https://user-images.githubusercontent.com/61637151/179359072-51648a6c-3821-43ef-89c9-55f7ca63e67b.png)




Also, I downloaded the mouse_processed.tar.gz, arranged the files given the folder structure in custom_object.md and ran the python predict.py script. My results are very different from the video you have attached. Please refer to the video below: 


https://user-images.githubusercontent.com/61637151/179359645-556a7b93-66c7-4cd2-a0db-87dbbed2c01b.mp4

I was wondering why the bounding box moves so erratically even though I am using the same mouse_processed files without any modification?

**Comment by liuyuan-pal** [comment]
Hi,
1. the matrix is [R;t] of 3x4, the first 3x3 matrix is a rotation matrix and the final 1x3 is a translation vector. It means the x_cam = R x_obj + t, where x_cam and x_obj mean the coordinate in the camera coordinate system and the object coordinate system respectively.
2. Maybe, you forget to transpose the input image? `--transpose` will transpose the image when splitting video into images. The `data/custom/mouse_processed/test/images_inter/0.jpg` will contain intermediate results of detection and viewpoint selection.

**Comment by omarirfa** [comment]
Thank you for clarifying the matrix! 

Regarding the transpose, I ran the code again using this code under custom_objects with the mouse video which was slightly modified to remove the / and to add the path ffmpeg.exe . 

`python predict.py --cfg configs/gen6d_pretrain.yaml 
                  --database custom/mouse_processed 
                  --video data/custom/video/mouse-test.mp4 
                  --resolution 960 
                  --transpose 
                  --output data/custom/mouse_processed/test 
                  --ffmpeg <path-to-ffmpeg-exe>`

I tried remaking my environment in anaconda using python 3.7, pytorch 1.12 along with CUDA 11.3 kit. Unfortunately, the mouse video is still the same. The intermediate results of detection also the same so I am a bit confused as to why the bounding boxes aren't as smooth. Do you think it could be something to do with python version or library versions install for packages? Could you please provide the python version maybe you are using along with pytorch ?

**Comment by liuyuan-pal** [comment]
Maybe, this is related to the version of opencv. It seems in my opencv version, using `--transpose` would correctly transpose the mouse image, so it looks like this:
![0](https://user-images.githubusercontent.com/23974453/179880818-3e22be6e-facc-4373-9d24-a6bed6f2047b.jpg)

My opencv version is 3.4.2. In your case, you might use the command without `--transpose`, that is 
```shell
python predict.py --cfg configs/gen6d_pretrain.yaml --database custom/mouse_processed --video data/custom/video/mouse-test.mp4 --resolution 960 --output data/custom/mouse_processed/test --ffmpeg <path-to-ffmpeg-exe>
```

**Comment by omarirfa** [comment]
My opencv version is 4.6.0.66, I tried without transpose the command, and it flipped all the inter images which were stored in the directory. The video output was also flipped.

images_inter directory:
![image](https://user-images.githubusercontent.com/61637151/179886773-d3628d7a-6d23-4c53-b11c-4f3189d27ca6.png)

images_inter:
![0](https://user-images.githubusercontent.com/61637151/179886879-ceca6555-97ef-4073-a96a-43151e6a2c5c.jpg)


Video:

https://user-images.githubusercontent.com/61637151/179888590-6c431261-35fe-4780-9e20-4ce111b5cbf4.mp4

Do you think I should try downgrading and running the command again?

**Comment by liuyuan-pal** [comment]
It seems that the images read from your video are all flipped upside-down. I think the problem is related to this issue
https://stackoverflow.com/questions/53097092/frame-from-video-is-upside-down-after-extracting
OpenCV changes its manner of reading video since 4.5
https://github.com/opencv/opencv/issues/15499
So I think downgrading opencv will be a direct solution.

**Comment by liuyuan-pal** [comment]
I have added codes to check the opencv version. I've checked that 4.6.0.66 works fine with this codes.
https://github.com/liuyuan-pal/Gen6D/blob/a36d1f864e02e6c5b18f9ed7066d568bb7b3ff6a/prepare.py#L29
Now, you still need the `--transpose` tag to run the prediction code
```
python predict.py --cfg configs/gen6d_pretrain.yaml --database custom/mouse_processed --video data/custom/video/mouse-test.mp4 --resolution 960 --transpose --output data/custom/mouse_processed/test --ffmpeg <path-to-ffmpeg-exe>
```

**Comment by omarirfa** [comment]
Works perfectly! Will be trying out with custom model now thank you for your help!

Images_inter for ref: 
![0](https://user-images.githubusercontent.com/61637151/180098847-b8dcc26e-cc84-4ed5-96d6-31a8fd45d1c0.jpg)
