### ISSUE TITLE
Realtime inference

### ISSUE THREAD

**Issue by apirrone** [liuyuan-pal/Gen6D#31]
Hello, 

Is there an easy way to compute the pose of a custom object in real time from a webcam stream for example ? 

Thanks !

**Comment by liuyuan-pal** [comment]
Hi, the current version is ~7fps on a 2080Ti GPU, and converting it to a faster one may require other techniques like network pruning, quantization, etc. It seems that there is no easy way to easily improve it for a real-time application. 
The detector and the selector are used in initialization, which can be discarded in the subsequent steps. Only the pose refiner is iteratively applied afterwards, so improving the efficiency of the refiner will be the most important part, which consists of a 2D VGG network and a 3D CNN network for pose regression.

**Comment by apirrone** [comment]
Ok, thank you for this information !
