### ISSUE TITLE
Pose estimation of multiple objects

### ISSUE THREAD

**Issue by mukuyo** [liuyuan-pal/Gen6D#34]
Dear Liu Yuan:
I want to detect pose estimation of multiple objects in one image. Is it possible with this network?

**Comment by liuyuan-pal** [comment]
Hi, current codes do not support multi-object pose estimation.
1. To estimate multiple different objects, you may need to run several Gen6D estimators for each object.
2. To estimate multiple instances of the same object, you may need to modify the detector to detect multiple objects and process them separately. The current detector only selects the pixel with the highest detection score as the bounding box. To detect several instances, you may need to specify a threshold to detect multiple instances. (I'm not sure about the performance)

**Comment by mukuyo** [comment]
I'm trying to detect multiple similar objects. But I don't know which threshold to change. I would really appreciate some help.

**Comment by liuyuan-pal** [comment]
I have not conducted experiments on the estimation of multiple objects so I do not know exactly how to set such a threshold either. If such a threshold is hard to set, maybe, you can first use a SOTA detector like YOLO to crop each object region. Then, you may apply the Gen6D estimator on each cropped region.

**Comment by lululovecode** [comment]
> I'm trying to detect multiple similar objects. But I don't know which threshold to change. I would really appreciate some help.

hello,I have faced the same problem as you said before,could you please help me about it now?Thank you a lot!
