### ISSUE TITLE
Contents of align of genmop dataset

### ISSUE THREAD

**Issue by mukuyo** [liuyuan-pal/Gen6D#38]
Dear Liu Yuan:
In each test file of the genmop dataset, there are align.pkl files. I would like to know what each value in the file represents and how it was generated.

**Comment by liuyuan-pal** [comment]
Hi, I manually label the same keypoint for two images in the reference sequence and two images in the query sequence. Then, I use triangulate to get the 3D coordinate of the keypoint in two sequences respectively. With 3 such keypoints, I'm able to compute a transformation between these two coordinates of the query and the reference.

**Comment by mukuyo** [comment]
Thank you for your replay. 

Can your method be done with cloud compare? It would be helpful if you could give me more details on how to achieve that. We apologize for the inconvenience and thank you for your support.

I apologize for the inconvenience this may cause.

**Comment by liuyuan-pal** [comment]
Hi, the tool for annotating the keypoints is https://github.com/luigivieira/Facial-Landmarks-Annotation-Tool
I actually label 5 points in a fixed order on each image, so that I can retrieve the correspondence by the index.
