### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by qz5k1** [liuyuan-pal/Gen6D#4]
Hi author,
     It's an amazing work.Whether the prediction module can be embedded in ROS.I used my own custom dataset. The effect is not very ideal. It is not clear whether it is a problem with the definition of the directions of X and Z.
 
![2022-07-16 16-53-20 的屏幕截图](https://user-images.githubusercontent.com/69182395/179347999-f057733d-3dfa-4da0-a0b6-d239c4f1f860.png)
![2022-07-16 16-54-46 的屏幕截图](https://user-images.githubusercontent.com/69182395/179348062-b3cf1c0d-4b45-4a9d-9b24-c5f668016127.png)

**Comment by liuyuan-pal** [comment]
Hi, you may try to downsample the query image to a smaller size because the reference images are all resized to 128 for detection and viewpoint selection. The detector and viewpoint selector will be used for the initialization of the poses, which assume the object in the query image looks relatively similar to the reference images in terms of scale and in-plane orientation (the given z-axis is the up direction).

**Comment by qz5k1** [comment]
> 嗨，您可以尝试将查询图像下采样到更小的尺寸，因为参考图像的大小都被调整为 128 以进行检测和视点选择。 检测器和视点选择器将用于姿势的初始化，假设查询图像中的对象在比例和平面内方向方面看起来与参考图像相对相似（给定的 z 轴是向上方向） .

Thank you, i will try it.

**Comment by liuyuan-pal** [comment]
To help debug the pose estimation process, I have updated the codes to visualize the pose initialization in `data/custom/mouse_processed/test/images_inter/0.jpg`.
It looks like this:
![0](https://user-images.githubusercontent.com/23974453/179349814-4af079d5-55e2-40ec-977a-fc29d1477e24.jpg)
And the subsequent pose refinement looks like this:
![666](https://user-images.githubusercontent.com/23974453/179350016-3c6cd996-9ede-4e1a-8ed8-218e7ced1691.jpg)

**Comment by qz5k1** [comment]
> 
Hi author！
      Thanks for the visual code. Through visualization, it is found that it may be because of the camera angle problem. The top features are actually very similar to the front features.
![0](https://user-images.githubusercontent.com/69182395/179353701-d0c97371-d503-4c4d-ba21-113604b08b59.jpg)
![52](https://user-images.githubusercontent.com/69182395/179353703-a9a10620-0fe3-493c-9c70-26fdf0d6ac6a.jpg)

**Comment by qz5k1** [comment]
Hi author,
     I would like to integrate your prediction module into ROS as object pose prediction. The robotic arm grasps by the recognized pose of the object. Can your prediction module do this?

**Comment by liuyuan-pal** [comment]
I'm not very familiar with the ROS system. It's supposed to be OK for grasping if we can predict the object pose [R;t] and know the object point cloud `object_point_cloud.ply`.

**Comment by qz5k1** [comment]
> 

Thanks for your answer.
