### ISSUE TITLE
Custom Model Training without Colmap 

### ISSUE THREAD

**Issue by Divyam10** [liuyuan-pal/Gen6D#44]
Hey @liuyuan-pal, thanks for publishing code for this amazing repo 

Can I use the custom detector without the colmap process. I have the following ground truth data. The mesh, synthetic RGB images, depth images, masks and ground truth poses. Basically, I have used Blenderproc to get the data. 

The reason for not using Colmap is depth ambiguity due to multi-view reconstruction, as you mentioned in one of the issues.

**Comment by liuyuan-pal** [comment]
Hi, as you can see, the COLMAP is providing poses for the `CustomDatabase` https://github.com/liuyuan-pal/Gen6D/blob/f95e82b075a5a61f9ef436c7756f4b07cffd172a/dataset/database.py#L238
So if you want to use your own data without COLMAP, you may need to implement a new `BaseDatabase` class similar to the `CustomDatabase` and replace it with any codes that use the `CustomDatabase`.

You may refer to how I process the LINEMOD database: https://github.com/liuyuan-pal/Gen6D/blob/f95e82b075a5a61f9ef436c7756f4b07cffd172a/dataset/database.py#L57

Hope this would be helpful!
Thanks!

**Comment by Divyam10** [comment]
I'll check it out. thanks!
