### ISSUE TITLE
colmap : WARNING: No images with matches found in the database.

### ISSUE THREAD

**Issue by blackHorz** [liuyuan-pal/Gen6D#46]
Hi There, I am not able to run the colmap code.

OS : Ubuntu 20

Here is the error for the same
'''
<pre>Loading cameras... 146 in 0.000s
Loading matches... 0 in 0.001s
Loading images... 146 in 0.000s (connected 0)
Building correspondence graph... in 0.000s (ignored 0)

Elapsed time: 0.000 [minutes]

WARNING: No images with matches found in the database.

ERROR: failed to create sparse model
Traceback (most recent call last):
  File &quot;prepare.py&quot;, line 98, in &lt;module&gt;
    build_colmap_model_no_pose(parse_database_name(args.database_name),args.colmap_path)
  File &quot;/home/fftai/working/6D Pose Estimation/Gen6D-main/colmap_script.py&quot;, line 104, in build_colmap_model_no_pose
    run_sfm(colmap_path, sparse_model_path, database_path, image_path)
  File &quot;/home/fftai/working/6D Pose Estimation/Gen6D-main/colmap_script.py&quot;, line 24, in run_sfm
    subprocess.run(cmd, check=True)
  File &quot;/home/fftai/anaconda3/envs/gen6d/lib/python3.7/subprocess.py&quot;, line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command &apos;[&apos;colmap&apos;, &apos;mapper&apos;, &apos;--database_path&apos;, &apos;data/custom/mouse/colmap/database.db&apos;, &apos;--image_path&apos;, &apos;data/custom/mouse/colmap/images&apos;, &apos;--output_path&apos;, &apos;data/custom/mouse/colmap/sparse&apos;]&apos; returned non-zero exit status 1.
</pre>
'''

Additional error to my code
'''
  Name:            139.jpg
  ERROR: Failed to extract features.
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
FilterH:	no kernel image is available for execution on the device
FilterV:	no kernel image is available for execution on the device
PyramidCU::GenerateFeatureList:	no kernel image is available for execution on the device

'''

**Comment by vaibhavholani** [comment]
I have the same issue

**Comment by liuyuan-pal** [comment]
It seems the COLMAP does not detect any images or matches in your COLMAP project. Maybe you need to delete the COLMAP project and process them again.

**Comment by XyWang-Austin** [comment]
I came across the same issue.
