### ISSUE TITLE
colmap

### ISSUE THREAD

**Issue by Ginger-X** [liuyuan-pal/Gen6D#53]
Hi, are you running on Windows or Linux, if Linux, how do I install colmap and find the path to colmap.exe, thanks

**Comment by liuyuan-pal** [comment]
I run it on linux.
It means the executable file of colmap.

**Comment by Ginger-X** [comment]
> I run it on linux. It means the executable file of colmap.

Thank you, I can open COLMAP by command "colmap gui", however I don't know that <path-to-your-colmap-exe> implies which of the following paths
![image](https://user-images.githubusercontent.com/65015349/221355107-e06696d2-a736-4fc5-b420-56d91e0a21a0.png)
![image](https://user-images.githubusercontent.com/65015349/221355128-eab085ab-3e7a-4581-8303-985cd04096fd.png)
I don't know where the executable file is, because it is opened with a command.

**Comment by liuyuan-pal** [comment]
It seems to be `build/exe/colmap`?

**Comment by Ginger-X** [comment]
> exe/colmap

Thank you very much!

**Comment by Azad99** [comment]
@Ginger-X Hi, may i ask how you install tha colmap? 
I am getting error at make -j4. 
Says "nvcc fatal unknown option '-fpic' "
