### ISSUE TITLE
预测结果偏差比较大

### ISSUE THREAD

**Issue by peng25zhang** [liuyuan-pal/Gen6D#71]
![0](https://user-images.githubusercontent.com/44889777/233021057-a31685e6-3b26-4abc-84db-2806a0634abc.jpg)
你好，我在predict custom data的时候，发现预测结果偏差比较大，请问下这个问题怎么优化比较好呢？

**Comment by peng25zhang** [comment]
非常感谢您的回复。还想问下，如果我想用上面这个水杯的数据finetune下 detector，只用生成GenMOP下类似的cup-ref文件夹里面的数据就行了吗？

**Comment by liuyuan-pal** [comment]
finetune这个比较复杂，你得看看训练代码的逻辑，得手动改改。这里没有提供直接finetune的接口，我暂时没有实现过finetune的代码。
