### ISSUE TITLE
Gen6D custom教程 Run COLMAP SfM to recover camera poses.

### ISSUE THREAD

**Issue by Xujc124** [liuyuan-pal/Gen6D#73]
这一步中的path-to-your-colmap-exe，是指哪个路径呢

**Comment by Xujc124** [comment]
我的系统是ubuntu20.04

**Comment by liuyuan-pal** [comment]
这里指的是你安装的colmap的可执行文件。

**Comment by Xujc124** [comment]
请问您当时运行第三步时基于的系统是Windows吗？

**Comment by liuyuan-pal** [comment]
并不是，这里在安装之后，会在colmap编译结果里面的bin文件里面找到一个叫colmap的可执行文件。

**Comment by liuyuan-pal** [comment]
https://colmap.github.io/install.html#linux

**Comment by Xujc124** [comment]
好的，已经找到了文件，我这边是colmap/build/src/exe文件中的可执行文件，感谢！
