### ISSUE TITLE
关于拍摄相机内参的问题

### ISSUE THREAD

**Issue by Xujc124** [liuyuan-pal/Gen6D#76]
请问作者大大，是否需要对拍摄视频的相机进行内参标定？

**Comment by liuyuan-pal** [comment]
如果你标定了应该会更准一点，我这里是直接猜了一个内参，f=sqrt(h**2+w**2)

**Comment by Xujc124** [comment]
如果我要把相机内参加到代码里，应该修改哪个文件呢？感谢回复

**Comment by liuyuan-pal** [comment]
reference image的话，应该你需要把f作为prior focal输入进去。
query image的K是在这里改的https://github.com/liuyuan-pal/Gen6D/blob/50aa71b2dbb3198772c025d54d0dd191a918982c/predict.py#L54

**Comment by Xujc124** [comment]
好滴好滴，感谢回复！
