### ISSUE TITLE
question about normalize

### ISSUE THREAD

**Issue by cugwzl** [liuyuan-pal/Gen6D#78]
有几个代码的问题，请教一下您
1）在Refinement阶段，再次坐标归一化是为了和构建的feature_volume对应吗
2）坐标归一化中，内参是怎么变化的，我不太理解这部分
3）您有试过将vgg换成res18吗
打扰您了，希望您能在闲暇时间回复一下

**Comment by liuyuan-pal** [comment]
1、2我不太明白你指的是我旋转了一下volume，还是那个对于坐标系的缩放和平移。缩放和平移是对改变了一下世界坐标系，得到一个新的世界坐标系，物体会在这个新的世界坐标系中的原点上单位球内。然后在refiner里面我有旋转一下，这里是让volume的朝向和query image的平面对齐。这两个操作都不会改变图像的内参。

3,这里我没有试过，不过我们这里本质上是个matching的过程，和matching的相关的网络一般VGG会比ResNet更好一点，比如SuperPoint等。

**Comment by liuyuan-pal** [comment]
但是detection之后把这个物体crop出来这一步，会涉及到内参的变化。我会把像主点更改为detection bounding box的中心，然后重新计算一个focal length。这里会产生一个图像上的homography transformation。

然后，我每次refine之后，我都需要用新的refined pose去算一个新的detection结果，然后更新这个detection的区域作为refiner的输入，所以我们要回到输入的query image上去重新crop，重新计算内参。这里涉及到的数学会有点绕。

**Comment by liuyuan-pal** [comment]
https://github.com/liuyuan-pal/Gen6D/blob/50aa71b2dbb3198772c025d54d0dd191a918982c/network/refiner.py#L290

这里是要把输入的pose更改到那个新的世界坐标系的坐标。因为输入的pose是原始物体坐标系的坐标。但是refiner自己是在那个新坐标系下处理的。

**Comment by cugwzl** [comment]
我再对照代码仔细理解一下。你回复的很快，还认真仔细，再次谢谢你！
此外，我还有个问题。我实际测试和你论文描述的一致，前面RT粗值精度很低，但在经过Refinement之后精度大大提高，能否理解您的这个工作主要是Refinment 在work。如果我想在您的baseline上进一步修改，提升粗估计的精度or提升refine的效果，哪个更可能work。

**Comment by liuyuan-pal** [comment]
嗯嗯，refiner在这里会起到比较主要的作用，但是detection和viewpoint初值还是不能太差，我感觉detection对于scale还是比较敏感，这个问题可能需要额外的处理。refinement我感觉已经算比较work了，除非用更大的数据集，可能你再训练refiner不会有太好的提升。

**Comment by cugwzl** [comment]
多谢你耐心的回复！
