### ISSUE TITLE
Reading pointcloud error

### ISSUE THREAD

**Issue by evdokimos** [liuyuan-pal/Gen6D#83]
Hello @liuyuan-pal, I created a pointcloud file for a custom object via CloudCompare and then saved it as a binary .ply file as you suggested, but when I try to run the predict.py script I keep getting this error 
`UnicodeDecodeError:'ascii' codec can't decode byte 0xce in position 0: ordinal not in range(128)  ` . Do you have something in mind about why I'm facing this problem? Thank you in advance!

**Comment by liuyuan-pal** [comment]
Sorry, I don't have exactly solution to this problem. Maybe, it is related to how you save and read the point cloud in binary or text mode? Maybe, you can try to read this directly to see whether it works or not.

**Comment by evdokimos** [comment]
I solved the issue by importing the **object_point_cloud.ply** file (which I extracted via Cloud Compare) in the colmap and then re-extracting it in .ply format. I don't know why it worked, I suppose that something is going on with the encoding of the .ply format

**Comment by Yuan-TS** [comment]
When cloudcompare exports a ply file, it will add a comment at the beginning of the file. You can refer to the following link to solve this problem: https://www.cnblogs.com/fusheng-rextimmy/p/15490029.html  @EvdoTheo
