### ISSUE TITLE
custom object

### ISSUE THREAD

**Issue by xczzz** [liuyuan-pal/Gen6D#88]

**Comment by xczzz** [comment]
根据 'custom_object.md' 中提供的方法，我使用我们自己的物体进行位姿估计，发现效果不太好，有许多位姿预测结果如下图所示。
![image](https://github.com/liuyuan-pal/Gen6D/assets/34471450/fbe8285f-2227-4842-afbb-a1b7a934400d)
请问这是否是因为物体纹理太少，或者背景杂乱引起的？

**Comment by liuyuan-pal** [comment]
你好，你可以参考一下这个issue，我怀疑是这个scale不太合适。https://github.com/liuyuan-pal/Gen6D/issues/29#issuecomment-1308379909

**Comment by xczzz** [comment]
我的理解是，这个物体scale太大了，对检测器产生了影响，所以在拍摄图像时，相机需要离物体远一些；参考图像和查询图像之间的scale比例应该在0.5~2之间。请问我的理解是否正确？

**Comment by liuyuan-pal** [comment]
嗯嗯，你可以看看中间结果，存在`data/vis_inter/gen6d_pretrain`里面。

**Comment by xczzz** [comment]
好的，我再重新拍摄图像试一下，感谢！

**Comment by douyizi** [comment]
你好，请问您解决了这个问题了吗？相机离物体远一些拍摄视频会有效果吗？
