### ISSUE TITLE
Issue with provided datasets

### ISSUE THREAD

**Issue by gaobaoding** [liuyuan-pal/Gen6D#9]
Dear authors,

thanks for your great work. I have problem with extracting the datasets. I've tried to decompress genmop and google-scanned datasets from your link, both have error "tar: Unexpected EOF in archive". I'm wondering if this happens during downloading or because of the compressed data itself. Could you comment on that? Thanks!

**Comment by liuyuan-pal** [comment]
Hi, the `genmop.tar.gz` file works fine on my computer with `tar xvf genmop.tar.gz`. Maybe, on your PC, the downloading is not completed or there are network connection problems when downloading?

**Comment by gaobaoding** [comment]
Hi Yuan,
Thanks for checking! Will close the issue :)
