### ISSUE TITLE
测试结果问题

### ISSUE THREAD

**Issue by xczzz** [liuyuan-pal/Gen6D#90]
作者你好，我用我们自己的物体构建了GenMOP数据集，并使用`eval.py`进行了评估。我输出了`eval.py`中的`pose_gt_list`，此外，我有物体准确的三维模型和相机内参，在测试图像上我标注了几个图像点，并用图像点和准确三维模型上对应的三维坐标，通过PnP计算物体位姿，发现PnP的结果与`pose_gt_list`中的差异很大，完全没有相关性，请问这个问题应该如何解释？如果我想把测试结果与PnP的计算结果进行比较，应该如何修改呢？

**Comment by xczzz** [comment]
请问，`eval.py`输出的物体位姿是在相机坐标系下的物体位姿吗？

**Comment by liuyuan-pal** [comment]
输出的pose是和这里的`database`得到的pose的坐标系一致的。
https://github.com/liuyuan-pal/Gen6D/blob/50aa71b2dbb3198772c025d54d0dd191a918982c/eval.py#L101
也就是说，这里取决于你的database是怎么读这个pose的。

**Comment by xczzz** [comment]
> 输出的pose是和这里的`database`得到的pose的坐标系一致的。
> 
> https://github.com/liuyuan-pal/Gen6D/blob/50aa71b2dbb3198772c025d54d0dd191a918982c/eval.py#L101
> 
> 
> 也就是说，这里取决于你的database是怎么读这个pose的。

请问Custom和GenMOP的database得到的pose坐标系有什么区别呢？

**Comment by liuyuan-pal** [comment]
你好，这里我们database的坐标系首先是colmap给定的，然后我们根据物体的object_point_cloud.ply以及z+ x+对它进行了缩放和旋转。对应的代码是这里
https://github.com/liuyuan-pal/Gen6D/blob/50aa71b2dbb3198772c025d54d0dd191a918982c/dataset/database.py#L281

**Comment by liuyuan-pal** [comment]
`x_cam = R x_world + t`这里的R和t表示pose。
如果你对世界坐标系进行了变换，`x_world_new = R_new @ x_world + t_new`， 你把这里的x_world解出来带入上面的式子就可以得到一个新的R t，和新世界坐标系的关系。
另外，如果你缩放世界坐标系，只会影响t，因为投影的时候会除以z，这样缩放是不影响投影后图像坐标的大小的。也就是说我对世界坐标系进行缩放 `x_cam = s R x_world + t`，那么对应的pose应该是 `x_cam = R x_wolrd + t/s`，两边同时除以s，但是左边的x_cam不受尺度影响。
