### ISSUE TITLE
detection problem

### ISSUE THREAD

**Issue by xczzz** [liuyuan-pal/Gen6D#96]
作者你好，我用我们自己的物体构建了类似LINEMOD的数据集，图像分辨率都是640*480，按照你给出的LINEMOD格式构建。训练集图像和测试集图像都来源于同一段视频数据，尺度基本一致。我重新训练了detector和refiner，但是发现下图所示的问题，
![1499-75-bbox](https://github.com/liuyuan-pal/Gen6D/assets/34471450/4d54319a-aec3-4943-bc4c-f4a7144985ab)
我的理解是，绿色框代表包围框真值，蓝色是预测的包围框，但是真值似乎是有问题的，导致最终预测的位姿误差很大。这个问题应该如何解决呢？

**Comment by liuyuan-pal** [comment]
这里感觉是gt的标注有一些问题。我这里有个关于如何制作genmop数据集的tutorial https://github.com/liuyuan-pal/Gen6D#how-to-make-a-genmop-object-for-evaluation

**Comment by xczzz** [comment]
请问您在用 LINEMOD database 训练detector时，使用的 2D box 真值是从哪里获得的呢？是从mask得到的吗？

**Comment by liuyuan-pal** [comment]
用3D pose的那个算出来的，3D object是在单位球内，可以算出来一个2D box。
