### ISSUE TITLE
Wrong results on custom object 

### ISSUE THREAD

**Issue by IAM-P-LP** [liuyuan-pal/Gen6D#97]
Hi,
I was trying to do the reproduce these results https://github.com/liuyuan-pal/Gen6D/blob/main/custom_object.md
This is what I obtained 
![image](https://github.com/liuyuan-pal/Gen6D/assets/54659792/7b5c700d-97ad-460b-9ef0-8b6455a43acd)
I was debugging where it went wrong.
After cropping the point cloud,this is what I got
![image](https://github.com/liuyuan-pal/Gen6D/assets/54659792/f04df0ba-e87b-400a-9936-a180749b8629)
Here,the yellow box which comes after cropping looks wrong.
Why the yellow box appears like this?Is there any issue in the point cloud I obtained?Can you please help on the same

**Comment by liuyuan-pal** [comment]
Hi, it seems that there is something wrong with your coordinate system.
![image](https://github.com/liuyuan-pal/Gen6D/assets/23974453/cd940567-d07f-457c-876c-b4d2a3493049)
The reference image is not centered on the object. You may check whether your object point cloud is aligned with the reconstructed points from the COLMAP project.

**Comment by IAM-P-LP** [comment]
Hi,Thanks a lot for your response.I was comparing your results and the results I got.
OBJECT_POINT_CLOUD(object_point_cloud.ply)
![image](https://github.com/liuyuan-pal/Gen6D/assets/54659792/ae3e5c50-8733-4414-83d4-0218234bf7bc)

AUTHOR’S OBJECT POINT CLOUD
![image](https://github.com/liuyuan-pal/Gen6D/assets/54659792/a065b347-6ff5-4f61-9247-0ad7b7e3af4b)

META_INFO FILE
2.610566 -0.679084 0.296952
-0.0456607 -0.562146 -0.825776
AUTHOR’S META FILE
2.396784 -0.617233 0.282476
-0.0452898 -0.550408 -0.833667


From images_inter folder,
![image](https://github.com/liuyuan-pal/Gen6D/assets/54659792/f61fa844-877d-4fd3-b893-a31ddb5036b2)
It almost looks the same.Can you please comment on how to proceed.

**Comment by liuyuan-pal** [comment]
The main reason for this could be that the `object_point_cloud.ply` is not in the same coordinate system as the COLMAP project i.e. `mouse/colmap/sparse/0`. If you run COLMAP again, then the coordinate system would change due to some randomness in the COLMAP. You could check that `mouse/points.ply` and `mouse/object_point_cloud.ply` are aligned or not. You may refer to https://github.com/liuyuan-pal/Gen6D/issues/12#issue-1331488161

**Comment by IAM-P-LP** [comment]
Thankyou.. It worked!
